name: Build

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Installing ninja
      run: |
        sudo apt install ninja-build libvulkan*
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
    - name: Build
      run: |
        cmake -B build -GNinja -DCMAKE_SYSTEM_NAME=linux -Dvenus=true && ninja -C build
    - name: Store virgl_test_server
      uses: actions/upload-artifact@v3
      with:
        name: virgl_test_server
        path: ./build
    
